name: Compile example paper

on:
  # Build any branch
  push:
    paths:
      - 'example/*'
  pull_request:
    paths:
      - 'example/*'
    # Build, but don't push on pull requests

jobs:
  build:
    name: Example PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        run: >-
          docker run \
              --volume "$(pwd):/data" \
              --user "$(id -u):$(id -g)" \
              openjournals/inara:latest \
              -o contextpdf,pdf,crossref,jats example/paper.md

      - name: Upload draft PDF
        uses: actions/upload-artifact@v3
        with:
          name: draft
          path: |
            example/paper.context.pdf
            example/paper.pdf
            example/paper.crossref
            example/paper.jats

      - name: Build Production PDF
        run: >-
          docker run \
              --volume "$(pwd):/data" \
              --user "$(id -u):$(id -g)" \
              openjournals/inara:latest \
              -o contextpdf,pdf,crossref,jats -p example/paper.md

      - name: Upload production PDF
        uses: actions/upload-artifact@v3
        with:
          name: production
          path: |
            example/paper.context.pdf
            example/paper.pdf
            example/paper.crossref
            example/paper.jats
